[model]
hidden_size = 1024
context_len = 168
pred_len = 24
continuous_loads = true

[pretrain]
batch_size = 256
init_scale = 0.02
warmup_steps = 10
lr = 0.01
scheduler_steps = 100
apply_scaler_transform = 'boxcox'

[transfer_learning]
apply_scaler_transform = 'boxcox'
